### ISSUE TITLE
Decide on an ETL / data engineering pipeline framework

### ISSUE THREAD

**Issue by ChasNelson1990** [road86/bahis-data#4]
### Problem

- We have 2 different generations of a database - BAHISv1 and BAHISv2 - and will soon have a third, BAHISv3.
- The point of bahis-data is to build a pipeline that can be run that pulls in the raw data from all three sources and processes that data to produce a single "ground truth" dataset.
- We need to develop pipelines that get the raw data from each source, tidy each data source independently, e.g. remove duplicates, correct known errors, etc., and then merge all three data sources into a single "ground truth" data set.
- We need to be able to add steps to these pipelines independently whenever new errors in the data are identified.
- We want to be able to version control these pipelines and the final data.
- We need this to be written in Python.

### Desired Solution

There are many tools out there for doing this. We should investigate them and decide which to use going forward, e.g. (off the top of my head):

- Apache Airflow
- Prefect
- Luigi
- DBT
- DVC

### Considered Alternatives

We can also just write this in Python and Pandas but one of these frameworks may be more useful for us?

**Comment by WaliZaman** [comment]
/home/wali/Downloads/motivation_whiteboard doodle.jpg

The reason for looking into these tools:
 • they will help in the management of the flows (making the computer manage it rather than a human)
 • dependencies are easier to handle

**Comment by mixmixmix** [comment]
I think we should also discuss what are our actual minimal requirements for this feature before commiting much effort to evaluate available tools https://github.com/road86/project-bahis/issues/157

**Comment by WaliZaman** [comment]
As the three shortlisted tools could not be run to successfully do the job, I will be shifting to custom python scripts.
