### ISSUE TITLE
Test the chosen data engineering tool on BAHIS data

### ISSUE THREAD

**Issue by sharful09** [road86/bahis-data#6]
- [x] Get the sql version of BAHIS data from Shariful
 - [ ] Get a pipeline ready to generate a tidied SQL file
 - [ ] Get a pipeline ready to generate an XLSX file

**Comment by WaliZaman** [comment]
The tools did not work out as expected and hence scrapped the idea of using a tool for now. Will try to use python for creating data pipelines.
